### ISSUE TITLE
Excepciones

### ISSUE THREAD

**Issue by davidroses02** [kiquebarbudo87/gestisimalkiquebarbudo.github.io#1]
Las excepciones son clases al igual que almacén o artículo, por ese motivo también deben de tener un comentario en su .java. Es decir, en las clases como articulo le pones un comentario por encima de la cabecera, pero en las clases de las excepciones no lo haces. @lmagarin

**Comment by kiquebarbudo87** [comment]
Hecho

**Comment by lmagarin** [comment]
Hola  @davidroses02. Muy bien explicado. Podrías haberle hecho referencia EXÁCTAMENTE a la línea de código
Y @kiquebarbudo87 , este issue no se cerró de forma automática desde el commit, ¿verdad?
